In [1]:
import numpy as np
from LinearRegression import LinearRegression

In [2]:
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([3.1, 4.9, 7.2, 8.8, 11.1])

In [3]:
model1 = LinearRegression.LRAnalytical()
model1.fit(X, y)
res1 = model1.predict(X)
print(res1)

[ 3.04  5.03  7.02  9.01 11.  ]


In [4]:
from sklearn import linear_model

In [5]:
skmodel1 = linear_model.LinearRegression()
skmodel1.fit(X, y)
skres = skmodel1.predict(X)
print(skres)

[ 3.04  5.03  7.02  9.01 11.  ]


In [6]:
from sklearn.linear_model import SGDRegressor

In [7]:
model = LinearRegression.LRStochastic(reg='l2')
model.fit(X, y, batch_size=1)
res = model.predict(X)
print(res)

[ 3.06444795  5.0544672   7.04448646  9.03450571 11.02452497]


In [8]:
model = LinearRegression.LRStochastic()
model.fit(X, y, batch_size=1)
res = model.predict(X)
print(res)

[ 3.03524031  5.02733977  7.01943923  9.01153869 11.00363815]


In [9]:
skmodel = SGDRegressor()
skmodel.fit(X, y)
res = skmodel.predict(X)
print(res)

[ 2.70508894  4.81261091  6.92013288  9.02765486 11.13517683]


In [10]:
model = LinearRegression.LRClassic()
model.fit(X, y)
res = model.predict(X)
print(res)

[ 3.02867203  5.02301172  7.01735141  9.0116911  11.0060308 ]


In [11]:
from sklearn import metrics

In [12]:
print("sklearn MSE:", metrics.mean_squared_error(y, skres))
print("My MSE:", LinearRegression.LossAndDerivatives.mse(X, y, model1.weights, model1.bias))

sklearn MSE: 0.02139999999999991
My MSE: 0.02139999999999985


In [13]:
print("sklearn MAE:", metrics.mean_absolute_error(y, skres))
print("My MAE:", LinearRegression.LossAndDerivatives.mae(X, y, model1.weights, model1.bias))

sklearn MAE: 0.13599999999999968
My MAE: 0.13600000000000073


In [14]:
print("sklearn MAPE:", metrics.mean_absolute_percentage_error(y, skres))
print("My MAPE:", LinearRegression.LossAndDerivatives.mape(X, y, model1.weights, model1.bias))

sklearn MAPE: 0.02075161926544409
My MAPE: 0.02075161926544472


In [15]:
print("sklearn R2:", metrics.r2_score(y, skres))
print("My R2:", LinearRegression.LossAndDerivatives.r2_score(X, y, model1.weights, model1.bias))

sklearn R2: 0.9973053289009771
My R2: 0.9973053289009771
